name: Meteo Marche Monitor - Allerte (Giornaliero)

on:
  schedule:
    # Esegue ogni giorno alle 06:00 UTC (corrisponde alle 08:00 ora legale italiana, 07:00 ora solare)
    # Modifica l'orario se necessario (es. '0 16 * * *' per le 18:00 italiane estive)
    - cron: '0 12 * * *'
  workflow_dispatch: # Permette l'avvio manuale

jobs:
  check_alerts:
    name: Controllo Allerte Meteo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests # Dipendenza necessaria

      - name: Run Alert Check Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        # Assicurati che il nome file sia corretto
        run: python alert_checker.py

      - name: Check script execution status
        if: failure()
        run: echo "Script Alert Check fallito!" && exit 1
