name: Meteo Marche Monitor

on:
  schedule:
    # Esegue ogni ora, al minuto 0
    - cron: '0 * * * *'
  workflow_dispatch: # Permette l'avvio manuale dalla UI di GitHub Actions

jobs:
  check_meteo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- NUOVO STEP ---
      - name: Update CA Certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y --only-upgrade ca-certificates
          # In alternativa, più forzato ma a volte necessario:
          # sudo apt-get install -y ca-certificates --reinstall
        # Potrebbe non essere necessario sudo a seconda dei permessi del runner, ma è più sicuro includerlo.

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Se usi requirements.txt:
          # pip install -r requirements.txt
          # Altrimenti (come prima):
          pip install requests

      - name: Run Meteo Check Script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python meteo_checker.py

      - name: Check script execution status
        if: failure()
        run: echo "Script execution failed!" && exit 1
