name: Check WeatherLink Thresholds

on:
  schedule:
    # Esegue ogni 30 minuti (puoi personalizzare)
    # Nota: GitHub Actions può avere ritardi, non è garantito al minuto esatto.
    - cron: '*/15 * * * *'
  workflow_dispatch: # Permette l'esecuzione manuale

jobs:
  check_weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # O la versione che preferisci

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests # Solo 'requests' è necessaria per questo script

      - name: Run weather check script
        env:
          # Passa i segreti come variabili d'ambiente
          WEATHERLINK_API_KEY: ${{ secrets.WEATHERLINK_API_KEY }}
          WEATHERLINK_API_SECRET: ${{ secrets.WEATHERLINK_API_SECRET }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python weather_alert.py # Assicurati che il nome del file sia corretto
